alertmanager:
  enabled: false
grafana:
  sidecar:
    dashboards:
      enabled: true
      label: grafana_dashboard
    datasources:
      enabled: true
  additionalDataSources:
    # - name: Prometheus
    #   type: prometheus
    #   url: http://kube-prometheus-stack-prometheus.monitoring.svc:9090
    #   access: proxy
    #   isDefault: true
    #   editable: true

    - name: Loki
      type: loki
      url: http://loki.monitoring.svc:3100
      access: proxy
      isDefault: false
      editable: true
