grafana:
  enabled: true
  adminPassword: prom-operator
  sidecar:
    dashboards:
      enabled: true
      label: grafana_dashboard
      folder: /tmp/dashboards
  additionalDataSources:
    - name: Prometheus
      type: prometheus
      url: http://kube-prom-stack-prometheus:9090
      access: proxy
      isDefault: true
  persistence:
    enabled: true
    type: pvc
    storageClassName: standard
    size: 10Gi
  extraVolumes:
    - name: dashboards
      persistentVolumeClaim:
        claimName: grafana-dashboards-pvc
  extraVolumeMounts:
    - name: dashboards
      mountPath: /tmp/dashboards
prometheus:
  prometheusSpec:
    scrapeInterval: "15s"
    storageSpec:
      volumeClaimTemplate:
        spec:
          storageClassName: standard
          resources:
            requests:
              storage: 10Gi
    additionalScrapeConfigs:
      - job_name: 'kubernetes-pods'
        kubernetes_sd_configs:
        - role: pod
        relabel_configs:
        - source_labels: [__meta_kubernetes_pod_annotation_prometheus_io_scrape]
          action: keep
          regex: true
        - source_labels: [__meta_kubernetes_pod_annotation_prometheus_io_path]
          action: replace
          target_label: __metrics_path__
          regex: (.+)
        - source_labels: [__address__, __meta_kubernetes_pod_annotation_prometheus_io_port]
          action: replace
          regex: (.+):(?:\d+);(\d+)
          replacement: $1:$2
          target_label: __address__