services:
  link-service:
    build:
      context: ./link_service
      dockerfile: Dockerfile
    environment:
      - LINK_TTL_SECONDS=86400
      - UVICORN_WORKERS=4
      - ROOT_PATH=/api
      - PORT=8000
      - AEROSPIKE_HOST=aerospike
    depends_on:
      - aerospike
    networks:
      - app-network

  redirect-service:
    build:
      context: ./redirect_service
      dockerfile: Dockerfile
    environment:
      - LINK_TTL_SECONDS=86400
      - UVICORN_WORKERS=4
      - PORT=8001
      - AEROSPIKE_HOST=aerospike
    depends_on:
      - aerospike
    networks:
      - app-network

  aerospike:
    image: aerospike/aerospike-server:7.0
    container_name: aerospike
    volumes:
      - aerospike-data:/opt/aerospike/data
      - ./aerospike/aerospike.conf:/etc/aerospike/aerospike.conf:ro
    ports:
      - "3000:3000"
      - "3001:3001"
      - "3003:3003"
    networks:
      - app-network

  nginx:
    image: nginx:1.26.0
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./frontend:/usr/share/nginx/html:ro
    depends_on:
      - link-service
      - redirect-service
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  aerospike-data:
    driver: local