services:
  link-service:
    build:
      context: ./link_service
      dockerfile: Dockerfile
    environment:
      - LINK_TTL_SECONDS=86400
      - UVICORN_WORKERS=4
    depends_on:
      - redis
    networks:
      - app-network

  redirect-service:
    build:
      context: ./redirect_service
      dockerfile: Dockerfile
    environment:
      - LINK_TTL_SECONDS=86400
      - UVICORN_WORKERS=4
    depends_on:
      - redis
    networks:
      - app-network

  redis:
    image: redis:7.4
    volumes:
      - redis-data:/data
      - ./redis/redis.conf:/usr/local/etc/redis/redis.conf
    command: redis-server /usr/local/etc/redis/redis.conf
    ports:
      - 6379:6379
    networks:
      - app-network

  nginx:
    image: nginx:1.26.0
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./frontend:/usr/share/nginx/html:ro
    depends_on:
      - link-service
      - redirect-service
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  redis-data: