services:
  aerospike-node1:
    image: aerospike:ce-8.0.0.7_1
    networks:
      - aerospike-net
    volumes:
      - aerospike-data1:/opt/aerospike/data
    configs:
      - source: aerospike_config
        target: /etc/aerospike/aerospike.conf
    hostname: aerospike-node1
    entrypoint: /usr/bin/asd --config-file /etc/aerospike/aerospike.conf --foreground


  aerospike-node2:
    image: aerospike:ce-8.0.0.7_1
    networks:
      - aerospike-net
    volumes:
      - aerospike-data2:/opt/aerospike/data
    configs:
      - source: aerospike_config
        target: /etc/aerospike/aerospike.conf
    hostname: aerospike-node2
    entrypoint: /usr/bin/asd --config-file /etc/aerospike/aerospike.conf --foreground

  aerospike-node3:
    image: aerospike:ce-8.0.0.7_1
    networks:
      - aerospike-net
    volumes:
      - aerospike-data3:/opt/aerospike/data
    configs:
      - source: aerospike_config
        target: /etc/aerospike/aerospike.conf
    hostname: aerospike-node3
    entrypoint: /usr/bin/asd --config-file /etc/aerospike/aerospike.conf --foreground

networks:
  app-swarm-net:

volumes:
  aerospike-data1:
  aerospike-data2:
  aerospike-data3:

configs:
  aerospike_config:
    file: ./aerospike.conf