global:
  scrape_interval: 15s

scrape_configs:
  - job_name: "docker"
    docker_sd_configs:
      - host: unix:///var/run/docker.sock
    relabel_configs:
      - source_labels: [__meta_docker_container_name]
        target_label: container
      - source_labels: [__meta_docker_image]
        target_label: image
      - source_labels: [__meta_docker_container_id]
        target_label: container_id

  - job_name: "loki"
    static_configs:
      - targets: ["loki:3100"] # Loki API для метрик
    metrics_path: /metrics
    relabel_configs:
      - source_labels: [__address__]
        target_label: instance