global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'cadvisor'
    dockerswarm_sd_configs:
      - host: unix:///var/run/docker.sock
        role: tasks
        filters:
          - name: service
            values: [mon_cadvisor]
        port: 8080
    relabel_configs:
      - source_labels: [__meta_dockerswarm_task_container_id]
        target_label: container_id
      - source_labels: [__meta_dockerswarm_node_hostname]
        target_label: node
      - source_labels: [__meta_dockerswarm_service_name]
        target_label: service_name

  - job_name: 'loki'
    static_configs:
      - targets: ['loki:3100']