apiVersion: v1
kind: ConfigMap
metadata:
  name: aerospike-config
  namespace: aerospike
data:
  aerospike.conf: |
    service {
      cluster-name aerospike-cluster
      # proto-fd-max 15000
    }
    logging {
      console {
        context any info
      }
    }
    network {
      service {
        address any
        port 3000
      }
      heartbeat {
        mode mesh
        mesh-seed-address-port aerospike-0.aerospike.aerospike.svc.cluster.local 3001
        mesh-seed-address-port aerospike-1.aerospike.aerospike.svc.cluster.local 3001
        address any
        port 3001
        interval 150
        timeout 10
      }
      fabric {
        address any
        port 3002
      }
    }
    namespace links {
      replication-factor 2
      max-record-size 1M
      storage-engine memory {
        data-size 256M
        stop-writes-avail-pct 5
        stop-writes-used-pct 70
        evict-used-pct 60
      }
    }